//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsManager.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string VoucherNotes { get; set; }
        public string Disclaimer { get; set; }
        public string RentMEVersion { get; set; }
        public bool IsActive { get; set; }
        public string LogoFilename { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public bool IsAssociatedAgency { get; set; }
    }
}
