//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedByUserId { get; set; }
        public int ReservationId { get; set; }
        public int ConceptId { get; set; }
        public int MethodId { get; set; }
        public double Amount { get; set; }
        public bool IsReimbursement { get; set; }
    }
}
