//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceConfiguration
    {
        public int Id { get; set; }
        public int CarCategoryId { get; set; }
        public int TourOperatorId { get; set; }
        public int SeasonId { get; set; }
        public int ReservationDayId { get; set; }
        public double CostPrice { get; set; }
        public double SalePrice { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
