//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDay
    {
        public int Id { get; set; }
        public int FromDay { get; set; }
        public int ToDay { get; set; }
        public bool IsActive { get; set; }
    }
}
