//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonDate
    {
        public int Id { get; set; }
        public int SeasonId { get; set; }
        public int FromDate { get; set; }
        public int ToDate { get; set; }
    }
}
